name: jd_action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: shshshfpa=f8f68320-dd9d-9048-9557-99f1e9a0d060-1691722900; shshshfpx=f8f68320-dd9d-9048-9557-99f1e9a0d060-1691722900; __jdu=1691722900651830460441; pinId=Z8TGPldCQPiRA3Ujm7iq4w; pin=Asurelike; unick=7hk27nk82ep9cc; _tp=jvkhggP1uAphxhaOlv%2BiTQ%3D%3D; _pst=Asurelike; o2State={%22webp%22:true%2C%22avif%22:false%2C%22lastvisit%22:1718160334620}; areaId=14; ipLoc-djd=14-1116-0-0; 3AB9D23F7A4B3C9B=TORMRCFYDMOW2227EP2MGRX4WFVPYPHNALEKID5ER6MJNG74WDLNWFYVSCXEFNDD4DP2XCPPMSR6COWVCVWNX3TBOE; TrackID=1GHoMEUqXfjwWf_7FSQt1oFWdo_-QAxWb5Ad5CDkQWWknWeyPis1eTstaUNPG6Hz4c1UHfJkP9v7_0Jix0WnPFcglmzKgBB4AzprgNIuHH5Xu482rf26KYENflKCp1-2T; thor=CF5DE37FCB0B951B448EB8F9756E9A0D9C066B381842FF751A5A18939B18ADB3CB4B71BDFBD0EF7853B2C3192988AB7B8412CD21A3EFCC9F4FA78383DBB5E4C1F361B9F7274AD8B722DA03970725E9A5EB7FB3B89793CF6886903E7D572963A3CB0CFD665631DBA949BAC24EEC441D70723B16D39D97B4A65405DB818E46BD17589A0D2B2A926DCE7FA1BA3C03C47E08; ceshi3.com=201; __jdc=76161171; PCSYCityID=CN_340000_340100_0; UseCorpPin=Asurelike; flash=2_odpDYUxzFR46lWFePEASihvsK43Z_pNJVumq8CnAHjOR9CJeKlVkaBzD2pdO3kMQgjJo_agq76ZwWWEQuml-kFSpnAW58-v1UATKoIPsQSwoXYS4gDeOI09HhbVEvTteOcnvBDsSVtrmTNzrGzsrA7FfJ6DxjjNuYIwnFOi2OrL*; unpl=JF8EAKFnNSttCkwBUBNXH0UWSVRTW1tcTh4GPDMDUVsKTF1QE1VJFRZ7XlVdWBRKER9uZRRUWlNKVA4aASsSEXtdU11UC3sQA25nDVJcW0NkBRwBEhEgSF1kX20ITB8DaWQGXFxZTFAFEgAaFxdKWFFebQl7FwtoVzVkWl1MUgwSBx8iEXtcZBUzCQYXBGdnA1deUEpVAh8CEhARTlpVW1gIexYzbA; __jda=76161171.1691722900651830460441.1691722901.1719992066.1719993661.44; __jdb=76161171.1.1691722900651830460441|44.1719993661; __jdv=76161171|c.duomai.com|t_16282_610197029|jingfen|c6dd9d5f738647e484be747c68d9fc67|1719993661320; 3AB9D23F7A4B3CSS=jdd03TORMRCFYDMOW2227EP2MGRX4WFVPYPHNALEKID5ER6MJNG74WDLNWFYVSCXEFNDD4DP2XCPPMSR6COWVCVWNX3TBOEAAAAMQO6OH6BAAAAAADUZT4STX753ZLEX; mt_xid=V2_52007VwMVWl1eUVkXSBhbAWcKEFNYX1NfGkkpWAFnBBRTDVFOWkpIGEAAblMTTg1aWggDT0xaA2UGGlNaDwYKL0oYXwB7AhROXFpDWhhCGFwOZgYiUm1YYlkYSxpVDGALFlpcaFZeHEs%3D; shshshfpb=BApXcEwyUdPVAAC0wL9p-_Cee8IZSZmG6B9MzLi9D9xJ1MnrwuIO2; 
  PUSH_KEY: SCT84742TxzCIMl6QAMEJMBHKPUPFl1s3
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


